typography_spectrum: 0.968
color:
  brandColors:
    - '#271d15'
    - '#c6c6c6'
    - '#495257'
    - '#a0afaf'
    - '#7292a3'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.3125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.498
analytics:
  google: null
  facebook: null
  twitter: null
name: Compendium
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: stuff
    url: bskn.co/inventory?alias=Cja__waLZKI
    type: external
favicon: null
purpose: []
